// src/lib/components/Preview.svelte
<script lang="ts">
	import * as Card from '$lib/components/ui/card';
	export let previewFiles: string[] = [];
</script>

<div class="grid grid-cols-3 gap-2">
	{#each previewFiles as file}
		<Card.Root class="overflow-hidden">
			<Card.Content class="p-0">
				<img src={file} alt="preview" class="aspect-square h-full w-full object-cover" />
			</Card.Content>
		</Card.Root>
	{/each}
</div>

// src/components/Preview.tsx
import type { PreviewFile } from '@/App'

interface Props {
  previewFiles: PreviewFile[]
}
export const Preview = ({ previewFiles }: Props) => {
  return (
    <>
      <div className='grid grid-cols-3 gap-4'>
        {previewFiles.map((file, index) => (
          <img
            key={index}
            src={file.url}
            alt={`preview ${index}`}
            className='aspect-square h-full w-full object-cover' />
        ))
        }
      </div>
    </>
  )
}
